### ISSUE TITLE
Not working on Unraid

### ISSUE THREAD

**Issue by sonuyos** [lancachenet/monolithic#104]
### Describe the issue you are having
I have downloaded lancache using community apps on my unraid server, however, i saw 2 problems.

1 - Origin does not work, it doesn't go through lancache, no matter what, i tried steamcache, and it worked there, however it doesn't work on lancache, when i ping to origin-a.akamaihd.net, it gives me the real server ip, however with steamcache, it works and gives me ip of steamcache, which is local.

2 - Now this is where it completely breaks, both lancache and steamcache. It shows that my steam games are caching, and i can see some files are there too, but when i try to delete and re-dwonload it just doesn't work. I am not sure what i am doing wrong, but both same. It redownloads from the internet instead of unraid.

### How are you running the container(s)

```
In Unraid
```

### DNS Configuration

```
Set it to 192.168.1.202, and touched nothing, doesnt work.
```

### Output of container(s)

```
Cannot find it in unraid, will gladly post if anyone can point it out to me.
```

**Comment by unspec** [comment]
Hi,

For question 1, yes, that is expected. Origin have enabled https downloads which breaks all attempts at caching. They have a potential http downgrade option being worked on at the moment (and it is in the origin beta client) but origin is disabled in lancache until they release this - monitor https://github.com/uklans/cache-domains/issues/98 for updates. 

I'm afraid I'm not familar with unraid, so i can't comment on how it does / doesn't work. We do have a note on it here: http://lancache.net/docs/common-issues/#unraid-port-bindings because its container implementation tends to break the required docker networking.

From your pc, if you do an `nslookup lancache.steamcontent.com` do you correctly get the IP of your lancache?

When you say "It shows that my steam games are caching", what do you mean by "it"? We really need the logs from the container to know what it is doing.

**Comment by sonuyos** [comment]
Hello,

I think origin did it, as I can see the cache in steam cache docker.

There is a recent release on community docker for lancache.

The lookup works correct.

It shows me the local ip.

By the statement you quoted, I mean that I can see the files being downloaded by the cache but does not download from cache when I reinstall.,

**Comment by unspec** [comment]
Hopefully somebody with some unraid experience may be able to help you troubleshoot running the containers in unraid.

In the mean time i would suggest following the advise here: http://lancache.net/docs/common-issues/#unraid-port-bindings and setting up a new ubuntu vm and then using our quick start guide http://lancache.net/docs/ to easily setup the required containers within it via docker-compose.

That should allow you to validate that lancache works and meets your needs in the meantime.

**Comment by sonuyos** [comment]
I was able to find the logs - http://www.filedropper.com/lancache

**Comment by unspec** [comment]
What does your cache log say? There will be a logs directory in your cache root in the VM (there was an option to set CACHE_ROOT in the .env file but it defaults to ./lancache/logs/ from wherever you ran the git command).  The access.log and error.log will show what lancache is doing for each request its getting.

Does it show lots of HIT or lots of MISS entries when you try to download a game for the second time? (The first time will be all MISS as the game is not yet in cache).

If you are correctly getting HITs the second time you download a game and its still slow, then its likely down to the hardware you are using. What sort of disks are in your server? What speed is your network etc. These containers are capable of serving thousands of gamers at the same time on the right (very high powered) hardware: http://lancache.net/docs/hardware/

**Comment by sonuyos** [comment]
Actually i am not the only one.

Here - https://www.reddit.com/r/DataHoarder/comments/f8w6kd/steamcache_not_working_on_unraid/fiq1is1/?context=3

Same problem having to someone else.

As for logs, they are pretty much normal.

in access.log it shows HIT and MISS both the second time it downloads. And its very flicky.

I think when i start steam and download it afresh (as in the cache is already there) it downloads fast, but after sometime it doesnt, it downloads off internet. (Though i cannot verify). 

I am really confused.

If you want i can show you on teamviewer.

**Comment by MathewBurnett** [comment]
The lancache-bundle app on unraid is not affiliated with this project. A third party has wrapped it up as an unraid app. Go see https://github.com/Josh5/lancache-bundle.

I use unraid at home and I am aware in its default storage configuration that disks are quite slow by caching standards as its setup for long term resilient storage. I would advise you to seek advice from the app maintainer as its very hard for us to know what unraid specific things they are doing.

**Comment by sonuyos** [comment]
> The lancache-bundle app on unraid is not affiliated with this project. A third party has wrapped it up as an unraid app. Go see https://github.com/Josh5/lancache-bundle.
> 
> I use unraid at home and I am aware in its default storage configuration that disks are quite slow by caching standards as its setup for long term resilient storage. I would advise you to seek advice from the app maintainer as its very hard for us to know what unraid specific things they are doing.

I have tried that, as well as ubuntu, both are same.

**Comment by MathewBurnett** [comment]
how does dns work in your network?

**Comment by unspec** [comment]
And do you have ipv6 enabled on your network?

**Comment by sonuyos** [comment]
> And do you have ipv6 enabled on your network?

Disabled it too, still same :(

**Comment by sonuyos** [comment]
> how does dns work in your network?

I do not understand your question.

**Comment by MathewBurnett** [comment]
Your client PC gets its dns server to use from something in your network. Have you set that manually? is it handed out by DHCP? do you have muliple dns servers set?

**Comment by sonuyos** [comment]
Hello

I have my router set to 8.8.8.8 and 8.8.4.4. but when using cache I set the
dns manually in networks setting. 192.168.1.xxx - ip of cache and 2nd box I
put 8.8.4.4.

Am I doing anything wrong?

**Comment by MathewBurnett** [comment]
and xxx is the ubuntu vm ip?

**Comment by sonuyos** [comment]
Yes, Ubuntu as well as unraid, i tried both, both same results.

**Comment by sonuyos** [comment]
Update - https://prnt.sc/r8m01d

Downloaded 350mb in steam, but on lancache only 45mb.

**Comment by MathewBurnett** [comment]
show me the dns servers in the output of `ipconfig /all`

**Comment by sonuyos** [comment]
https://prnt.sc/r8malg here

> show me the dns servers in the output of `ipconfig /all`

**Comment by MathewBurnett** [comment]
you have two dns servers set so it will use both, hence some of your requests don't hit the cache. Stop using 8.8.8.8 on your client

**Comment by sonuyos** [comment]
I cannot enter same IP twice in the DNS. It doesnt allow.

**Comment by sonuyos** [comment]
Also, i cannot use internet without adding 8.8.8.8.

**Comment by MathewBurnett** [comment]
you should set your client to talk to the container on 192.168.1.206 and then have the upstream dns on the dns container set to 8.8.8.8 , if you don't do that then you will not be using the container to get your dns all of the time and it won't work.

**Comment by sonuyos** [comment]
Upstream dns is already set to 1.1.1.1 and it still doesn't work.

**Comment by MathewBurnett** [comment]
Lets have one last look at your setup ...
1) Are you are running the docker-compose on a vm now?
2) If so can you show me the env file?
3) can you also show me `docker ps`?

**Comment by sonuyos** [comment]
Nah i removed the vm as i gave up on that.

Right now its on Unraid only.

https://ibb.co/MVDhRwj

Config on unraid docker

**Comment by MathewBurnett** [comment]
ok then we are back to pointing out the specifics of the lancache-bundle are nothing to do with us see (https://github.com/lancachenet/monolithic/issues/104#issuecomment-590918798) and we don't know what it may or may not be doing. You clearly have a dns issue in your network.

**Comment by sonuyos** [comment]
I can try to install ubuntu and try with it. But it gives same result.

If I have DNS issue then it should be visible too right, I just can't find
any issue.

**Comment by MathewBurnett** [comment]
your issue is that you have multiple client dns servers defined and that you don't have a correctly configured dns container that you can talk to that can talk out to its upstream dns.

**Comment by sonuyos** [comment]
But I have even checked linus' setup and even there they used 1.1.1.1 for alternate dns.

As for dns container there is literally nothing I have edited, I have left everything as it is. Also I am not the only one who is facing this issue.. so many people are facing it too.

**Comment by MathewBurnett** [comment]
> As for dns container there is literally nothing I have edited,
you mean you didn't edit someone else's unraid community app?

**Comment by sonuyos** [comment]
I meant the setting.

It isn't someone else's apps setting. The setting is done by the person who is running the container. And same issue is replicated even in Ubuntu VM.

**Comment by unspec** [comment]
On your pc:

- Remove any DNS server other than your container's ip
- Do `ipconfig /flushdns`
- Then do `nslookup lancache.steamcontent.com`
- and `nslookup www.google.com`

Do you get any results? If so, what?

**Comment by sonuyos** [comment]
Here - https://prnt.sc/r8oc8e

**Comment by unspec** [comment]
Right, so it looks like the container can do upstream lookups ok, so you shouldnt need to add a second dns server to your pc. As mentioned doing that means your pc may end up caching the "none poisoned" dns results for some records.

You should now see all of the game download going via the cache.

**Comment by sonuyos** [comment]
I tired, it still doesnt work.

https://prnt.sc/r8oeol

1.2GB downloaded of boneworks, but shows only 1.4gb on cache (787mb was there from Jurassic World download).

https://prnt.sc/r8ofbf

1.9GB downloaded, cache is 1.6g,

**Comment by sonuyos** [comment]
There is literally no other dns - https://prnt.sc/r8ogi7

i ipconfig /flushdns too

https://prnt.sc/r8ogxw

It just doesnt want to fuckin work :(

https://prnt.sc/r8oh4p

Not going past 1.6G now.

**Comment by unspec** [comment]
Did you restart steam and/or your pc after flushing dns? Steam will cache certain IPs internally.

**Comment by sonuyos** [comment]
Yup

**Comment by sonuyos** [comment]
Downloaded 950mb from previous.

1GB of Boneworks, yet it remained at 1.2GB 

https://prnt.sc/r8tnys

It just doesnt cache.

**Comment by VibroAxe** [comment]
Can we see the access.log and error.log please?

**Comment by sonuyos** [comment]
bind() to 0.0.0.0:80 failed is only there cuz i was trying to bind to ip which was in use (Unraid Main IP, didnt work).

[error.log](https://github.com/lancachenet/monolithic/files/4266171/error.log)

[access.log](https://github.com/lancachenet/monolithic/files/4266170/access.log)

**Comment by Lepidopterist** [comment]
Having looked at the access log, it bears absolutely no resemblance to our access.log format.  This would lead me to believe that whatever you are running is either (a) not based on any of our work or (b) at least three years old and entirely unsupported.

I would suggest you ask for vendor support from whoever made the Unraid package.  We are unable to provide support on this.

**Comment by sonuyos** [comment]
Funny thing, it was updated yesterday itself. Want me to setup ubuntu and try on that?
