### ISSUE TITLE
Lancache and core count

### ISSUE THREAD

**Issue by malteserr** [lancachenet/monolithic#106]
Hi there,

I'm planning on caching content for a small LAN party and I'll admit I'm very new to docker and lancache with limited time to run my own tests. I have a choice of two CPUs (systems) for the build, all other variables such as RAM and storage remaining equal:

Intel Atom C2758 with 8 cores at 2.4Ghz
Intel Core i5-5200U with 2 cores/4 threads at 2.7Ghz (seemingly hugely better single core performance)

What would you recommend in this case?

Thank you in advance!

**Comment by MathewBurnett** [comment]
I wouldn't expect a massive difference between the two. I expect the i5 is probably the stronger of the two chips. You are more likely to be bottled necked on disk speed or amount of memory.

**Comment by malteserr** [comment]
Thank you @MathewBurnett, thinking about it I'm guessing CPU is indeed the least critical part of speccing out the system for my use-case
