### ISSUE TITLE
Maybe add mobile app store cache #enhancement

### ISSUE THREAD

**Issue by DewetTDS** [lancachenet/monolithic#110]
Pls add Google Play Store and IStore

**Comment by unspec** [comment]
Unfortunately previous testing has shown that almost all of this sort of mobile / app update traffic is Https (i.e encrypted) and thus uncacheable.

If anyone has any information or testing to the contrary we'd be interested to see it, but as far as we know this is not currently possible.

**Comment by DewetTDS** [comment]
K
