### ISSUE TITLE
Blizzard caching

### ISSUE THREAD

**Issue by DrProfSagi** [lancachenet/monolithic#113]
### Describe the issue you are having
blizzard caching perfoance

### How are you running the container(s)
Running on ubuntu 20.04 with pihole on raspbarry pi as dns server

### The issue
As far as i can tell, the proccess for caching blizzard, is more of a readahead interval instead of inline caching, what i mean is that istead of both pulling from blizzard and passing to my pc, it only pulls a chunk, then let my pc read it, then pulls another chunk, and so on, resulting in a very flexuating download, from 8mb/s, to 0, going back and forth with the speed.
It does not happen to me in steam
I have increased slice size with no luck

**Comment by MathewBurnett** [comment]
the cache does that for all sources, however the speed calculation that gives you a number in the battlenet launcher seems very sensitive to it. While some users have played with the slice size for their combination of hardware and internet speed i usually advise sticking with the default. The best measure of what is really going on is to watch your router incoming bandwidth on a fresh install and see how much of the line you are saturating. At home I get between 60-90% but we have had reports of people having difficulties.
