### ISSUE TITLE
lancache only caches 500GB

### ISSUE THREAD

**Issue by Nerr1x** [lancachenet/monolithic#114]
### Describe the issue you are having

The Lancache container is only caching up to 500GB.
The standard setting is still active with 1000000m and the host VM and the container OS recognize over 1.1TB of disk space

### How are you running the container(s)

Standard config

docker run --restart unless-stopped --name lancache-dns --detach -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=$HOST_IP -e UPSTREAM_DNS="1.1.1.1; 1.0.0.1" lancachenet/lancache-dns:latest
docker run --restart unless-stopped --name lancache --detach -v /cache/data:/data/cache -v /cache/logs:/data/logs -p 80:80  lancachenet/monolithic:latest
docker run --restart unless-stopped --name sniproxy --detach -p 443:443 lancachenet/sniproxy:latest

### DNS Configuration

DNS is probably not the issue

### Output of container(s)

There are no issues in the lancache container in the last 7 days

**Comment by shinji257** [comment]
That seems strange.  I checked my local cache and it is approaching 1TB.

```
shinji@game-cache:/cache$ sudo du -h -d1
[sudo] password for shinji:
1.6G    ./logs
4.0K    ./cachedomains
977G    ./data
979G    .
```
```
shinji@game-cache:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  1.4M  1.6G   1% /run
/dev/sda2       6.0T  986G  4.7T  18% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sda1       511M  6.1M  505M   2% /boot/efi
/dev/loop0       97M   97M     0 100% /snap/core/9436
/dev/loop1       97M   97M     0 100% /snap/core/9665
tmpfs           1.6G     0  1.6G   0% /run/user/1000
```
