### ISSUE TITLE
Steam game never downloads and repeated hits in access.log

### ISSUE THREAD

**Issue by alkenerly** [lancachenet/monolithic#115]
### Describe the issue you are having
I newly setup monolithic on my network and decided to test it out using Skyrim. The cache seems to be working great as I see many MISSes in the access.log then those turn to HITs when I delete and restart the download. 

However, I am actually seeing that skyrim never finishes downloading. It acts normally for the first 3GB or so then I can see that the client repeatedly requests the same chunks over and over again.

### How are you running the container(s)

I am hosting on a local unraid server using josh5/lancache-bundle:latest

docker run -d --name='lancache-bundle' --net='br0' --ip='192.168.1.202' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'LANCACHE_IP'='192.168.1.202' -e 'DNS_BIND_IP'='192.168.1.202' -e 'CACHE_MEM_SIZE'='2000m' -e 'CACHE_DISK_SIZE'='4000g' -e 'CACHE_MAX_AGE'='150d' -e 'UDP_PORT_53'='53' -e 'UPSTREAM_DNS'='192.168.1.1' -e 'USE_GENERIC_CACHE'='true' -e 'DISABLE_ARENANET'='' -e 'DISABLE_BLIZZARD'='' -e 'DISABLE_CITYOFHEROES'='' -e 'DISABLE_DAYBREAK'='' -e 'DISABLE_EPICGAMES'='true' -e 'DISABLE_FRONTIER'='' -e 'DISABLE_HIREZ'='' -e 'DISABLE_NEVERWINTER'='' -e 'DISABLE_NEXUSMODS'='' -e 'DISABLE_NINTENDO'='' -e 'DISABLE_ORIGIN'='' -e 'DISABLE_RENEGADEX'='' -e 'DISABLE_RIOT'='' -e 'DISABLE_ROCKSTAR'='' -e 'DISABLE_SONY'='' -e 'DISABLE_STEAM'='' -e 'DISABLE_TESO'='' -e 'DISABLE_TWITCH'='' -e 'DISABLE_UPLAY'='' -e 'DISABLE_WARFRAME'='' -e 'DISABLE_WARGAMING'='' -e 'DISABLE_WSUS'='' -e 'DISABLE_XBOXLIVE'='' -v '/mnt/user/lancache':'/data/cache':'rw' -v '/mnt/user/appdata/lancache-bundle/log/named':'/var/log/named':'rw' -v '/mnt/user/appdata/lancache-bundle/log/nginx':'/var/log/nginx':'rw' 'josh5/lancache-bundle:latest' 

### DNS Configuration

I am on windows and set my DNS server to 192.168.1.202 so that it queries the lancache bundle. This seems to work for general internet browsing etc. 

### Output of container(s)

This is the access.log for the issues I am describing. Let me know if any other logs are needed.

![lancache problem](https://user-images.githubusercontent.com/24815164/88831610-94847200-d19d-11ea-8262-d8e4c3b6aa17.PNG)

**Comment by YowaC** [comment]
Hi,
this is possibly a problem from some allowing-to-write-there stuff....
You shoud check that the folder of your lancache data is owned by user and group www-data

`ls /your/path/to/lancache/folder -ali`

it should output sth like this:

```
1469 drwxr-xr-x  3 root     root     4096 Oct  6 23:38 .
   2 drwxr-xr-x 23 root     root     4096 Oct 25 09:48 ..
   ...
   2 drwxr-xr-x  6 www-data www-data 4096 Oct 10 14:11 lancache
   ...
```

If not then:
you have to chown www-data:www-data your folder where your cache is located. For example:
`chown www-data:www-data /mnt/lancache` (change "/mnt/lancache" to your directory where your data is stored on your machine).

Also please check that it is enough space availabe on the cache-disk.
To check this do the following as root:
`df -h`

The output should look somewhat like this:

```
root@steamcache:~# df -h
Filesystem                                       Size  Used Avail Use% Mounted on
udev                                             1.9G     0  1.9G   0% /dev
tmpfs                                            380M  4.2M  376M   2% /run
/dev/mmcblk0p2                                    30G  4.5G   24G  17% /
tmpfs                                            1.9G   12K  1.9G   1% /dev/shm
tmpfs                                            5.0M     0  5.0M   0% /run/lock
tmpfs                                            1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/loop0                                        49M   49M     0 100% /snap/core18/1883
/dev/loop1                                        49M   49M     0 100% /snap/core18/1888
/dev/loop3                                        27M   27M     0 100% /snap/snapd/9611
/dev/loop2                                        63M   63M     0 100% /snap/lxd/16945
/dev/loop4                                        27M   27M     0 100% /snap/snapd/9730
/dev/loop5                                        64M   64M     0 100% /snap/lxd/16103
/dev/mmcblk0p1                                   253M   96M  157M  38% /boot/firmware

/dev/mapper/usbhdds-lv_lancache                  4.6T   55G  4.3T   2% /mnt/lancache

overlay                                           30G  4.5G   24G  17% /var/lib/docker/overlay2/c241ff87f1efd7ccf67a8aace511eb3af0fe54c6f0e17ee1bc69d242ef108430/merged
overlay                                           30G  4.5G   24G  17% /var/lib/docker/overlay2/7104e2d63b861c475362bd8f499f75bca97f83e6f9691d5eab79d01ed64e15d4/merged
overlay                                           30G  4.5G   24G  17% /var/lib/docker/overlay2/ad252922b3fab97c1b3d99f74bfdd7967aaf5a14f40ea6c3752d2e50e7073b27/merged
tmpfs                                            380M     0  380M   0% /run/user/1000

```
**(I seperated the line for you that you will need, ATTENTION, this could look very different for your system)**
If you're space use is at 100% consider to free some disk space.
