### ISSUE TITLE
Running multiple instances of lancachenet/monolithic

### ISSUE THREAD

**Issue by darki73** [lancachenet/monolithic#116]
### How are you running the container(s)

```
Running them in Unraid via Docker interface, each container on it's own IP address (192.168.2.201-204 for monolithic and 192.169.2.200 for DNS)
```
![image](https://user-images.githubusercontent.com/1318627/92037098-1ed46e80-ed26-11ea-9150-d8ca4f7afd37.png)

### DNS Configuration
```
Not using generic cache, specifying IPs for each service i want to cache the data from
```
![image](https://user-images.githubusercontent.com/1318627/92037222-50e5d080-ed26-11ea-84ce-47f1e2694367.png)

### Server Specs
**Processor:** Ryzen Threadripper 2970WX
**Memory:** 128GB Kingston ECC 3200Mhz
**Network Interface Card:** Aquanta 10Gbit

All files initially downloaded to `1TB Samsung Evo 970 NVMe` drive, so IO is not a bottleneck, then they are transferred to 7200 HDD

### Output of container(s)

My question is, i am seeing an increase in speed download in all clients (initial download), however, when i am using `docker stats` the amount of data received by the containers is NOT what the client shows.

So is it worth running multiple containers for `monolithic` with one DNS container? Is it a mistake (the amount downloaded in the `docker stats` versus the actual download) that the downloaded amount does not match?

And one more question, is `monolithic` able to determine if the cached version of a chunk already exists or it simply overwrites the data? I've followed the **Adding more IPs** guide, and ended up with 1.2G downloaded in the client and 1.2G * 4 containers in the `docker stats`

Here is how my `nslookup` looks like
![image](https://user-images.githubusercontent.com/1318627/92037725-0f095a00-ed27-11ea-819c-62dd5ea5037b.png)

**Comment by MathewBurnett** [comment]
When a file is requested monolithic will fetch it from the internet if missing or hand it our if cached already. 

I have not found docker stats to be particularly accurate when it comes to net/disk io.
