### ISSUE TITLE
Any way to update specific cache contents?

### ISSUE THREAD

**Issue by ArmedAviator** [lancachenet/monolithic#117]
I am using lancache monolithic, lancache-dns and lancache-sni dockers on a Void Linux virtual machine with no issues.  I added a few additional domains for my Void Linux and Ubuntu repositories that I use in-house.  This is great for all of the PCs, laptops, and VMs I am running.  The problem is that the repository file indicating what the current package versions are does not get redownloaded since it is a cache hit.

Is there any way to have specific files not be cached - or - specific files/domains force a file header date/size checked?

To be specific, I am trying to update the cache for this file for starters:
http://mirror.clarkson.edu/voidlinux/current/x86_64-repodata

**Comment by VibroAxe** [comment]
@ArmedAviator not without creating your own container

However, if you did want to you should be able to inherit from our container and add a single file to the overlay  which uses the same mechanic as the LOL updated:
https://github.com/lancachenet/generic/blob/master/overlay/etc/nginx/sites-available/generic.conf.d/10_generic.conf

You'd probably want the file to be in `overlay overlay/etc/nginx/sites-available/generic.conf.d/root/voidlinux.conf`
