### ISSUE TITLE
run without docker

### ISSUE THREAD

**Issue by totayma** [lancachenet/monolithic#120]
Hello,

how to run lancache without docker container. i want to setup it to bare metal server.
thanks

**Comment by MathewBurnett** [comment]
All the info on how configs are created is contained in these open sources projects. However as our focus is on a docker based approach we are not intending to write a guide on how to achieve it separately.  If you would like to figure it our you are welcome to do so. I would advise looking at the nginx configs inside a working container to get you started

**Comment by apefrei** [comment]
I have been working on a script for baremetal implementation. However, I haven't had the time to maintain it lately. Maybe it gives you some idea on how you could do it: https://github.com/apefrei/lanparty-linux-server

**Comment by VibroAxe** [comment]
@apefrei I'm curious why when your bootstrap already installs docker why you would then extract the configs instead of just pulling our preconfigured docker images?

If you think you are worried about performance you'll find the docker overhead to be negligible, performance limitations are usually the network/disk/client

**Comment by apefrei** [comment]
@VibroAxe The bootstrap does a basic installation for our physical hosts. Docker only gets installed to you chose to start the corresponding subscript. We do not mix the docker, linuxgsm or nginx parts on one host.

Our cache server has a specific hw configuration which allows us to use nginx hash-split caching. So I had to modify the config for our environment anyway. Also I didn't use sniproxy but nginx ssl preread. While doing so, i thought it would be best to get rid of the docker overhead. I have never benchmarked anything, so i can't tell if this realy makes any difference.

Docker is perfect for our smaller services, like intranet, ranking system, teamspeak and so on...

**Comment by VibroAxe** [comment]
Fair enough. For relevance our base image now uses sni preread instead of sniproxy. I've not played around with hash split enough to look at what it would do. Thanks for the input
