### ISSUE TITLE
Steam client on linux not hitting cache any longer

### ISSUE THREAD

**Issue by wanginator** [lancachenet/monolithic#128]
### Describe the issue you are having
Hi folks, I'm seeing an issue with the steam client on linux hitting the cache on both my rig and laptop.  Have no idea where to look to troubleshoot.  

I'm positive the cache is functioning correctly because the EGS, Ubi Connect and Guild Wars 2 all hit the cache without issue.  Same with all other devices on my network. (PS4, PS5, Xbox, several other windows machines, etc.)

The other kicker is, when I boot to windows on the same machine, the cache functions as expected.  Same with the laptop.

Ideas are welcome

### How are you running the container(s)
 
Unraid docker container

**Comment by csamsel** [comment]
Probably a different DNS server ip / resolver is used on the machine.

**Comment by Magissia** [comment]
Was not able to replicate, my cache server receives requests on port 80 just buy setting the lancache subdomain as per Valve's instructions on router's dnsmasq configuration.

DHCP properly serves my hosts the router as DNS and hits are made.
