### ISSUE TITLE
EA Desktop installed apps are not cached

### ISSUE THREAD

**Issue by shinji257** [lancachenet/monolithic#129]
### Describe the issue you are having
EA Desktop installed applications are not being cached.  This is likely due to use of HTTPS as there doesn't appear to be any cache server detection or an option to use insecure connections in this client.

### How are you running the container(s)
I don't really have a command line since I use portainer so I'll screenshot and give you the container configuration from it.
![image](https://user-images.githubusercontent.com/261005/112213567-97344b80-8bf4-11eb-897a-0b54d0e800bf.png)

### DNS Configuration
Router -> Steam Cache DNS -> 8.8.8.8 upstream

The router only uses the Steam Cache DNS server and doesn't have any other DNS on it.  Not even the ISP DNS.

### Output of container(s)
No output.  It doesn't even hit.  I did do some checking on DNS/SNI logs though and found it still hits origin-a.akamaihd.net but that is routing through sniproxy and so it must be doing it via HTTPS.

**Comment by shinji257** [comment]
As an added note Origin itself still works.  It is just EA Desktop that is affected at the moment.

**Comment by PacketShepard** [comment]
Any update on getting EA Desktop working or forcing it to detect a cache?

**Comment by JackBailey** [comment]
Still seems to not be caching them for me

**Comment by lprhodes** [comment]
I'm going to have a look at what servers EA is using within the EA desktop app, hopefully it's as simple as adding new hosts to the lancache-dns repo.

**Comment by lprhodes** [comment]
So EA are downloading via HTTPS and also ignoring the system proxy settings making it hard to catch the data through more common means.

I may try and capture the traffic via a local VPN but it's probably more hassle than it's worth.,

**Comment by shinji257** [comment]
They also never reimplemented the option from Origin to let you use http connections for the content servers. This is what made caching possible in the first place.

**Comment by tpill90** [comment]
@VibroAxe This is another common question.  There's no fix for this, but it would be worth adding to the FAQ or known issues on the docs.
