### ISSUE TITLE
Steam: Cannot create collection

### ISSUE THREAD

**Issue by reitermarkus** [lancachenet/monolithic#141]
### Describe the issue you are having

I cannot create a steam collection while LanCache is active. It tries to access `https://ufs00375.steamcontent.com:8699/ugcupload`, and port 8699 is obviously not routed through the cache.

I guess the solution would be to also proxy port 8699, but from reading https://github.com/lancachenet/monolithic/issues/85, it seems that using a cache domains repo with `lancache.steamcontent.com` as the only Steam-related domain should also work. Is there a known `cache-domains` fork with only the `lancache.steamcontent.com` domain?

### How are you running the container(s)

Kubernetes (Monolithic + DNS)

### DNS Configuration

PiHole -> LanCache DNS (pointing to Monolithic) -> Unbound

### Output of container(s)

N/A

**Comment by mintopia** [comment]
Thanks for reporting this to us. We've created a branch of cache-domains `feature/reduce-steam-domains` which only contains `lancache.steamcontent.com` required for Steam to detect the cache.

Please feel free to use this one, we will ensure it is updated with any other changes from master.

The aim is to trial this over the next month and if there's no problems, update master to only use this domain for Steam.

**Comment by GotenXiao** [comment]
Worth noting that we ended up having to revert uklans/cache-domains#124 via uklans/cache-domains#162, as there was a Steam client bug on Linux. No idea if that client bug has since been resolved.
