### ISSUE TITLE
Star Citizen Cache?

### ISSUE THREAD

**Issue by MachineGalaxy** [lancachenet/monolithic#142]
Would it be possible to add the Star Citizen launcher to the service so the game data could be cached?

**Comment by GotenXiao** [comment]
See [this issue](https://github.com/uklans/cache-domains/issues/33) tracking the RSI launcher; traffic is HTTPS-only and delivered via CloudFront, so it's not likely in the near term.

**Comment by MachineGalaxy** [comment]
Ahh, Ok.
Thanks

**Comment by ryankurte** [comment]
howdy, i couldn't find a matching issue in the RSI tracker so have created one, but it would need some "reproductions" by folks with star citizen to be confirmed. https://issue-council.robertsspaceindustries.com/projects/LAUNCHER/issues/LCH-768
