### ISSUE TITLE
Setup with multiple NVMEs without RAID

### ISSUE THREAD

**Issue by XatinaRah** [lancachenet/monolithic#150]
I’m trying to setup a environment without raid, with multiple NVMEs, but I can’t find a way to this inside .env file or with manual docker variables. Anyone has already tried such setup ? Thanks.

**Comment by unspec** [comment]
Lancache only supports being passed a single path in which to store its cached data.

It doesn't much care what the underlying disk structure under that is (although we would always recommend some form of resiliency), but it does need it presented as a single volume.

You could use something like LVM or other volume management features to span a single volume over multiple non-raided disks, or even something like a RAID0, but again not something we would recommend.
