### ISSUE TITLE
LANCache is clearing cached data with 7TB left on the share

### ISSUE THREAD

**Issue by TheRedHerring95** [lancachenet/monolithic#155]
### Describe the issue you are having
LANCache deleting cache data after approximately 800-900GB cached. 

### How are you running the container(s)

```
The official apps on UnRAID, default settings but custom dedicated IPs for DNS and cache, downloading to a single share on a single SSD.
```

### DNS Configuration

```
DNS is the LANCache DNS container, set in Windows. DNS works, and caching hits until it starts clearing cached data; not DNS issue.
```

### Output of container(s)

```
Not sure where to find this on the first place, happy to provide them if needed. May need guidance on how to get them. 
```

Edit: Assuming the default is the same for the UnRAID app/docker as the main repo (which I'm assuming it is), I'm guessing it's that it's hitting the CACHE_DISK_SIZE limit, as that variable isn't exposed to the UI in UnRAID. I'm currently searching for the location for the config to add it manually if I can. If there's a way to add it through the UI, that would be excellent, otherwise help finding the configuration file would be great. Folders selected in case that helps: 
Logs folder: mnt/user/lancache/logs
Cache folder: mnt/user/lancache

**Comment by VibroAxe** [comment]
There are no official apps on UnRAID! Our advice is to install lancache using the official guide using an unraid VM. From what you've said above I am assuming you are using the Josh5 bundle. Please raise an issue over at https://github.com/Josh5/lancache-bundle/issues

**Comment by VibroAxe** [comment]
@TheRedHerring95 do you have a link to these?

**Comment by TheRedHerring95** [comment]
Not on hand right now, but I can grab them and post them when I get a chance. I'll put the links to both the cache and the DNS when I do.

**Comment by TheRedHerring95** [comment]
Sorry, for the delay, I forgot when I got home. The links to the projects for it are both to lancache.net, with the registry listed as here, so it definitely seems to just be referring to the container as an app. 'Official' badge isn't there on the main screen at this point because of it already being installed (shows an 'Installed' badge there instead). 
![image](https://user-images.githubusercontent.com/12248386/194674662-edbf884e-7bb0-4057-acd3-42ba4aea5dc6.png)
![image](https://user-images.githubusercontent.com/12248386/194674748-301fea1e-dd39-4afb-9be9-144c333fe60c.png)
