### ISSUE TITLE
perm check change

### ISSUE THREAD

**Issue by KillahB33** [lancachenet/monolithic#168]
### Describe the issue you are having
Hey Team, I am trying to do lancache using my nas, perm check will fail then try to chown files which will then fail so monolith will never start
UID:99 and group users
This is the nobody user on unraid

### How are you running the container(s)

```
docker compose up -d
```

### DNS Configuration

```
<!-- Paste your docker run command for the DNS container OR explain how you have setup DNS on your network to point to the container -->
```

### Output of container(s)

```
# Finished including /etc/nginx/nginx.conf
Checking nginx config
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] chown("/data/cache/cache", 33) failed (1: Operation not permitted)
nginx: configuration file /etc/nginx/nginx.conf test failed
ERROR: hook /hooks/supervisord-pre.d/99_config_check.sh} returned a non-zero exit status '0'
```

**Comment by VibroAxe** [comment]
Are you using nfs by any chance?

**Comment by VibroAxe** [comment]
Yeah you will do. NFS will be squashing the root user which the init scripts are run as to nobody, so it has no permission to read or create folders. Check out no_root_squash command line options for your NFS mount. Not sure if it exists in v4

**Comment by KillahB33** [comment]
There seems to be a miss understanding here. The user would have permission to read and create folders so that shouldn't be an issue.
