### ISSUE TITLE
Add support for easy cleaning

### ISSUE THREAD

**Issue by VibroAxe** [lancachenet/monolithic#170]
A file can be "cleaned" from the cache using the below command from the host
`find /your/cache/folder -type f -exec awk 'FNR>2 {nextfile} /depot\/236391\/chunk\/cdd60ddacb14bd7d57e20c6972df2c1136d3e6f5/ { print FILENAME ; nextfile }' '{}' +`

Add support to the docker container to allow easy cleaning using something similar to `docker exec lancache_monolithic_1 clean <slug>`

**Comment by Dimensional** [comment]
Can we get a breakdown of this command for us uninitiated who want to clean files out but do not know if they have them?

**Comment by VibroAxe** [comment]
The `FNR>2` is important as it only searches the top two lines. You could `head|grep&&rm` but the awk is more efficient as you don't have the process overhead. Remember you have 65536 folders in a lancache environment, before you go into the numbers of files within a folder! Processing overhead on this command is important.

**Comment by tpill90** [comment]
@VibroAxe This one is still valid.  We get a decent number of questions on Discord on how to handle this.   At the least the documentation on the project docs could be improved to make it clearer on how to handle this.  There is also [lancache-chunk-purge](https://github.com/tpill90/lancache-chunk-purge) that I wrote that could be included as a solution for this in some way, or it could be integrated into what you started with #176
