### ISSUE TITLE
Expose nginx status from http_stub_status_module

### ISSUE THREAD

**Issue by luser** [lancachenet/monolithic#189]
I was looking into using telegraf to scrape nginx metrics from lancache into InfluxDB. The telegraf nginx agent wants to hit the nginx status page for some stats. It looks like the `/nginx_status` endpoint is configured in the base image:
https://github.com/lancachenet/ubuntu-nginx/blob/8adad4dcdea7297f7de386bd8cf8ef5fc21b8d2d/overlay/etc/nginx/sites-available/status.conf#L5

…but those site configs get removed in this repo's Dockerfile:
https://github.com/lancachenet/monolithic/blob/8392ba66134c719a161d1cc083afeef146d6190a/Dockerfile#L26

I can hack this up myself for local usage but it would be nice if this worked out-of-the-box.

**Comment by VibroAxe** [comment]
Metrics are available on port 8080

https://github.com/lancachenet/monolithic/blob/master/overlay/etc/nginx/sites-available/30_metrics.conf
