### ISSUE TITLE
Docker Image Update

### ISSUE THREAD

**Issue by igloo15** [lancachenet/monolithic#194]
### Describe the issue you are having

Docker image updates with no changes to repo. I did docker compose update recently and noticed the docker images have been updated in the last 20 days. I was interested to know what changed in the image so I checked the website and saw the last news article was from 2022. I went on github and saw there hasn't been a commit since last year. So I am wondering what are the updates and how is the image changing despite no changes in the repo?

### How are you running the container(s)

Standard Docker Compose from git

### DNS Configuration

N/A

### Output of container(s)

N/A

**Comment by VibroAxe** [comment]
The image rebuilds monthly to make sure we pull in the latest security updates from the upstream images.

**Comment by igloo15** [comment]
> The image rebuilds monthly to make sure we pull in the latest security updates from the upstream images.

Thanks I recommend adding this as a note somewhere in documentation or repo. DNS is a pretty big security vulnerability area so anytime something that handles my DNS requests updates I think its very important to understand what changes have occurred. I am glad to hear that the updates are automated security updates but I think its important to document that somehow.
