### ISSUE TITLE
Steam missing cache

### ISSUE THREAD

**Issue by nyemenzo** [lancachenet/monolithic#22]
### Describe the issue you are having
after  moving from steamcache to monolithic i got no HIT. and prematurely closed error. i got this error. all of them. i triead all the games i have but no luck. 

### How are you running the container(s)?
```
i fork your mono and change env repo uklans/cache-domain to nyemenzo/cache-domain
```

### DNS Configuration
```
steamcache dns. also change uklan/cache-domain to nyemenzo/cache-domain
```
### Output of container(s)
```
*528 upstream prematurely closed connection while reading upstream, client: 192.168.8.100, server: , request: "GET /depot/731/chunk/36597b40d7290ee2ebe4cee5252d49759435258b?etime=1552520138&h=0893ee6b8582e7be1a502 HTTP/1.1", upstream: "http://67.24.11.252:80/depot/731/chunk/36597b40d7290ee2ebe4cee5252d49759435258b?etime=1552520138&h=0893ee6b8582e7be1a502", host: "level3.cdn.steampipe.steamcontent.com"
2019/03/07 00:36:33 [error] 220#220: *530 upstream prematurely closed connection while reading upstream, client: 192.168.8.100, server: , request: "GET /depot/731/chunk/c2749c4f76eb8b13a765e1cdf0a93eca1241d280?etime=1552520138&h=0893ee6b8582e7be1a502 HTTP/1.1", upstream: "http://67.24.13.252:80/depot/731/chunk/c2749c4f76eb8b13a765e1cdf0a93eca1241d280?etime=1552520138&h=0893ee6b8582e7be1a502", host: "level3.cdn.steampipe.steamcontent.com"
```

**Comment by VibroAxe** [comment]
@nyemenzo did this go away? We've not had anyone else reporting this issue so it was either a steam issue or a local config issue?

**Comment by VibroAxe** [comment]
Or possibly you are trying to cache a domain in nyemenzo/cache-domain which isn't valid

**Comment by shinji257** [comment]
Not necessarily the same issue but close.  Here is what I've noticed.  For the most part Steam uses HTTP but if there is an error it seems to switch to HTTPS.  The above premature error message may be a trigger.  I'm able to verify this through the resource monitor and netstat where it may stop transferring over port 80 and instead just use 443.

Currently I'm at home and not where Monolith is being used but while downloading an update I see it using a mix of port 80 and 443 connections to what I believe are the CDN servers.  The HTTPS ones bypass the cache and end up going through sniproxy.

So with that said does anyone know if there is a way to force Steam to use HTTP all the time regardless of any errors it may hit?

Error log excerpt gist: https://gist.github.com/shinji257/a5911bfacc1d100ffa5054d2db58d487

**Comment by unspec** [comment]
Closing as no response from the original submitter. Plus Steam & HTTPS in general will be resolved under their new update - see https://github.com/lancachenet/monolithic/issues/85
