### ISSUE TITLE
Unable to resolve github.com

### ISSUE THREAD

**Issue by bensmithy123** [lancachenet/monolithic#23]
Describe the issue you are having
container is unable to resolve github.com so never downloads lancache domians file - therefore all requests for content also get cannot be resolved

I have tried removing the container, redownloading and clearing the cache folder etc already.
From the host machine I can ping github.com so I am unsure why the container cannot get through to this.

Worth noting this worked up until roughly a week ago and then suddenly stopped so steam downloads etc tend to just sit at zero till they fail. All other containers are having no issues connecting to the web etc so any help is greatly appreciated. Thanks

How are you running the container(s)?
docker run -d --name='Monolithic-Cache' --net='br0' --ip='192.168.11.202' --privileged=true -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'UPSTREAM_DNS'='1.1.1.1 8.8.8.8' -e 'CACHE_DISK_SIZE'='100g' -e 'BEAT_TIME'='1h' -v '/mnt/user/steamcache/':'/data/cache':'rw' -v '/mnt/user/appdata/steamcache/':'/data/logs':'rw' --restart unless-stopped --cap-add=NET_ADMIN 'steamcache/monolithic'

DNS Configuration
docker run -d --name='Monolithic-DNS' --net='br0' --ip='192.168.11.201' --privileged=true -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'USE_GENERIC_CACHE'='true' -e 'UPSTREAM_DNS'='1.1.1.1' -e 'LANCACHE_IP'='192.168.11.202' -e 'STEAMCACHE_IP'='192.168.11.202 192.168.11.203 192.168.11.204 192.168.11.205 192.168.11.206 192.168.11.207 192.168.11.208 192.168.11.209 192.168.11.210 192.168.11.211' --restart unless-stopped 'steamcache/steamcache-dns'

Output of container(s)
Output from app log in unraid:
Executing hook /hooks/entrypoint-pre.d/10_setup.sh
Executing hook /hooks/entrypoint-pre.d/15_generate_maps.sh
Cloning into '.'...
**fatal: unable to access 'https://github.com/uklans/cache-domains.git/': Could not resolve host: github.com**
fatal: not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
jq: error: Could not open file cache_domains.json: No such file or directory

map $http_host $cacheidentifier {
hostnames;
default $http_host;
}
Executing hook /hooks/entrypoint-pre.d/19_doc_root_setup
/var/www/html already exists.
Setting document root to /var/www/html
Executing hook /hooks/entrypoint-pre.d/20_perms_check.sh
Checking permissions (This may take a long time if the permissions are incorrect on large caches)...
Permisions ok
Executing hook /hooks/entrypoint-pre.d/20_ssl_setup
Not enabling SSL as neither key nor cert provided.
Executing hook /hooks/supervisord-pre.d/20_test_files_setup
Checking if /var/www/html is empty - Directory not empty.. don't touch content
Executing hook /hooks/supervisord-pre.d/21_cleanup_log_files
Cleaning up log files older than 3560 days
Executing hook /hooks/supervisord-pre.d/99_config_check.sh
Checking nginx config
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Config check successful
2019-03-09 13:32:18,714 CRIT Set uid to user 0
**fatal: unable to access 'https://github.com/uklans/cache-domains.git/': Could not resolve host: github.com**
fatal: not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
jq: error: Could not open file cache_domains.json: No such file or directory

Also, from access log:
2019/03/09 12:59:55 [error] 59#59: *30 level3.blizzard.com **could not be resolved** (110: Operation timed out), client: 192.168.11.3, server: , request: "HEAD /tpr/ovw/config/ff/c6/ffc61aeb5e49e0fba7f90245ca9d273b HTTP/1.1", host: "level3.blizzard.com"

**Comment by bensmithy123** [comment]
Think I finally found my issue - for some reason .202 was just not working, moved to .203 and now works perfectly. Can be closed unless there is an underlying issue here?

Checked my router and made sure there were no overlapping IPs etc but saw nothing - strange really..

**Comment by itsRems** [comment]
I've got the same error - except changing ips wont do anything

**Comment by bensmithy123** [comment]
@itsrems is that won't or hasn't? If you haven't tried it then please do as I still cannot work out why it worked but it did.

**Comment by itsRems** [comment]
I've tried - didn't work. Also tried changins dns, docker ip, etc.. nothing.
Note that I have another docker instance running under a different IP

**Comment by VibroAxe** [comment]
@itsrems have you specified the upstream dns?

**Comment by itsRems** [comment]
> @itsRems have you specified the upstream dns?

Yup

**Comment by VibroAxe** [comment]
Could you give the full container log please?

**Comment by itsRems** [comment]
> Could you give the full container log in a new issue please?

need to reconfigure some things before running it again but I'll do it asap
