### ISSUE TITLE
Data Information Script Thing

### ISSUE THREAD

**Issue by DarrenRainey** [lancachenet/monolithic#33]
Hello for those interested I wrote a quick script here: https://github.com/DarrenRainey/Script-Bin/blob/master/Sys%20Admin/Steamcache-Monolithic-Data-Stats.sh to display lancache stats as seen below:
![Screenshot from 2019-05-21 17-18-32](https://user-images.githubusercontent.com/6136439/58112978-824b9300-7bec-11e9-9f25-d47eed1dd630.png)

**Comment by VibroAxe** [comment]
@DarrenRainey interesting idea here, how does it perform on large log files?

**Comment by DarrenRainey** [comment]
currently the largest file I've test was around 500MB and it took a few minutes to parse it although I will note that I am using a low power APU and running the OS of a old SD Card reader so results may vary.

I may look into improving the speed later but at the moment this works and uses tools that are ussally installed by default on many distro's however if you want to go even faster you could look at the sift tool which is a faster alternative to grep.

**Comment by unspec** [comment]
I've tagged this for-reference and will close as no specific outstanding questions. 

Feel free to reopen if there are any futher developments or additional useful info.

**Comment by HeedfulCrayon** [comment]
It would actually be nice to have stats like this displayed either in a webpage on the lancache, or via an API request
