### ISSUE TITLE
LanCache.net shows incorrect docker container names

### ISSUE THREAD

**Issue by EgonSpengler** [lancachenet/monolithic#35]
### Describe the issue you are having
https://lancache.net shows docker commands which use a nonexistent repository name (`lancache/<container>` rather than `lancachenet/<container>`).

This results in a "repository does not exist" error and probably some confused users :)

**Comment by Lepidopterist** [comment]
Thanks for that.  Just waiting on the PR to be approved to fix.

**Comment by VibroAxe** [comment]
Fixed!

**Comment by EgonSpengler** [comment]
Oh my apologies, I didn't realize the site itself was based on the repo or I would have submitted the fix myself.  Thanks!
