### ISSUE TITLE
Windows Update cache not working

### ISSUE THREAD

**Issue by marcquark** [lancachenet/monolithic#37]
### Describe the issue you are having
Using a very basic setup as proposed in the manual, my caches are working just fine. However Windows Update seems to be troubled. I get the error message "We couldn't connect to the update service. We'll try again later, or you can check now. If it still doesn't work, make sure you're connected to the Internet". It appears every time i click on the check for updates button.
I believe the problem has to do with the sniproxy. I can see that it's passing some traffic along, but my PC never tries to actually download anything:
2019-06-08 13:32:50 X.X.X.X:7257 -> Y.Y.Y.Y:443 -> 13.68.93.109:443 [sls.update.microsoft.com] 4027/4027 bytes tx 507/507 bytes rx 0.514 seconds
2019-06-08 13:32:50 X.X.X.X:7259 -> Y.Y.Y.Y:443 -> 13.74.179.117:443 [sls.update.microsoft.com] 4027/4027 bytes tx 507/507 bytes rx 0.289 seconds
2019-06-08 13:32:50 X.X.X.X:7260 -> Y.Y.Y.Y:443 -> 13.74.179.117:443 [sls.update.microsoft.com] 4027/4027 bytes tx 507/507 bytes rx 0.249 seconds
2019-06-08 13:32:50 X.X.X.X:7261 -> Y.Y.Y.Y:443 -> 13.74.179.117:443 [sls.update.microsoft.com] 4027/4027 bytes tx 507/507 bytes rx 0.236 seconds
2019-06-08 13:32:51 X.X.X.X:7262 -> Y.Y.Y.Y:443 -> 13.74.179.117:443 [sls.update.microsoft.com] 4027/4027 bytes tx 507/507 bytes rx 0.247 seconds
2019-06-08 13:32:51 X.X.X.X:7263 -> Y.Y.Y.Y:443 -> 13.68.93.109:443 [sls.update.microsoft.com] 4027/4027 bytes tx 507/507 bytes rx 0.483 seconds
2019-06-08 13:32:51 X.X.X.X:7264 -> Y.Y.Y.Y:443 -> 13.74.179.117:443 [sls.update.microsoft.com] 4027/4027 bytes tx 507/507 bytes rx 0.240 seconds
2019-06-08 13:32:52 X.X.X.X:7265 -> Y.Y.Y.Y:443 -> 13.74.179.117:443 [sls.update.microsoft.com] 4027/4027 bytes tx 507/507 bytes rx 0.238 seconds

DNS is working fine. My PC resolves the relevant hostnames to the IP address of the lancache/sniproxy container

As a temporary workaround, i started the DNS container with DISABLE_WSUS=true. However it would be great if the problem could be resolved somehow, because windows update caching would really speed up my network (3+ Windows 10 clients and a slow connection are no fun at all)
Maybe whitelisting sls.update.microsoft.com specifically could already be enough, because it looks like Windows first queries this address via HTTPS to check for available updates before downloading them (from another address) over HTTP. The HTTPS traffic can't be cached anyway.

### How are you running the container(s)?
Pretty much exactly as described under "Simple Full Stack Setup". However i use seperate IPs to bind the DNS and HTTP/HTTPS ports to.

### DNS Configuration
Statically configured my PC to resolve via the steamcache-dns container IP address. This is working fine:
C:\Users\xxxxxx>nslookup sls.update.microsoft.com
Server:  396d88284d7c
Address:  Z.Z.Z.11

Non-authoritative answer:
Name:    wsus.cache.steamcache.net
Address:  Z.Z.Z.12
Aliases:  sls.update.microsoft.com

### Output of container(s)
see description above, no additional relevant output

**Comment by VibroAxe** [comment]
Been testing a bunch of configurations of the cache this weekend and I can't reproduce this at all?

**Comment by It0w** [comment]
Hi its exactly the same for me ...

For the Windows-Clients to Update i periodically bypass the dns :)

![update](https://user-images.githubusercontent.com/13597836/68190280-662a8b00-ffad-11e9-9d3a-9ee2998ab59c.jpg)

**Comment by csamsel** [comment]
I guess it's related to #65

**Comment by It0w** [comment]
ah seems so :D 

thank you

**Comment by Lepidopterist** [comment]
Hey all,

I don't have a running LanCache instance to test with at the moment, but we have an event coming up at the end of November, where we'll be able to run a full flight of tests against it.

Windows Updates were never really a primary focus of the cache, and the hostnames have been added 'ad hoc' as they have been spotted.  However, we've never deeply investigated the hosts in the list so it's highly possible there are some issues.

PR's are accepted if you do find hostnames that you believe should not be cached :)

**Comment by It0w** [comment]
Hi,

i have used ```https://github.com/bntjah/lancache``` for a while. And I can remember that Microsoft was also causing trouble there. I think a solution was found in this Issue ```https://github.com/bntjah/lancache/issues/37``` 
I hope this maybe help somewhat

**Comment by drobskind** [comment]
Hello, I am experiencing the same issue for month now.
Each and every LAN-Party I am hosting, having this issue. Don't unterstand the label "can't replicate" there are a few people having this issue.
Is there anything I can do to support here? 

Greetings from Berlin

**Comment by It0w** [comment]
Hi,
i run the docker-image with
```-i DISABLE WSUS=true``` command
to bypass the dns

also greetings from berlin :)

**Comment by drobskind** [comment]
Hi lt0w,
i know this command. But I'd rather have it working with windows update as well. The internet connection we have in place here is only 12mbit/s.
LANCache is a great invention for this. So thanks all developers for doing such a great job.
So please have a look at the topic. Not sure if the hint from 15th november 2019 is helpful. 
Next LAN-Party is scheduled for end of Feb.

Greetings from Berlin.

**Comment by marcquark** [comment]
i just tested this with the most recent containers and DNS lists.
it seems to work so far. i'm installing windows updates as i type, and can see requests hitting the cache server. maybe #65 fixed it. i'm running lancache at home so i can observe the next couple of patch tuesdays. will continue to report.

**Comment by marcquark** [comment]
for reference, it stopped working a few days later...

**Comment by tyrfing666** [comment]
Was having a similar problem with Windows Updates. Updated and restarted Lancache this morning. Still "Can't contact update server."

Added DISABLE_WSUS=true to the .env file and restarted again.

Can now contact Update server and can download updates. Something odd is going on with the cache.

**Comment by VibroAxe** [comment]
We made some changes to the domains files and images around windows update. If you are having these issues make sure that all your containers are up to date with latest.

**Comment by marcquark** [comment]
@VibroAxe lookin' good here even after a couple of weeks!

**Comment by VibroAxe** [comment]
Thanks @marcquark
