### ISSUE TITLE
[RFE] Add FAQ entry for lancache-autofill?

### ISSUE THREAD

**Issue by Da-Geek** [lancachenet/monolithic#45]
### Feature Request/Question
I would like to try and manually pre-seed the cache before an event, due to the fact the event will have terrible connectivity, and I have 1Gbps/1Gbps connection at home.

I know I could just uninstall/reinstall all of my games, but I was hoping to have some way to run a command or poke a URL/API to ask the cache to download the content, so will act more like an initial download server during the event as well as a cache.

I would of course prefer to turn up to the event with a cache that already has a large amount of the content in the cache, so we can reduce the initial load on the events crappy internet connection.

**Comment by unspec** [comment]
Something like https://github.com/zeropingheroes/lancache-autofill might be worth looking at for you

**Comment by Da-Geek** [comment]
Why is this not in the FAQ :-)

**Comment by VibroAxe** [comment]
It's a good question. #HelpWanted
