### ISSUE TITLE
Steam client won't update

### ISSUE THREAD

**Issue by BurningTheSky** [lancachenet/monolithic#49]
### Describe the issue you are having
On one machine the client says it is up to date but hasn't updated since I started using the cache. I just did a fresh install on another machine and it said I needed to be online to update the client. As soon as I point the DNS away from the cache it updated fine.

### How are you running the container(s)?
docker run --restart unless-stopped --name lancache --detach -v /cache/data:/data/cache -v /cache/logs:/data/logs -p 192.168.1.81:80:80 -p 192.168.1.82:80:80 -p 192.168.1.83:80:80 -p 192.168.1.84:80:80 -e CACHE_MEM_SIZE=4000m -e CACHE_DISK_SIZE=1000g  steamcache/monolithic:latest
docker run --restart unless-stopped --name wsuscache --detach -v /wsus/data:/data/cache -v /wsus/logs:/data/logs -p 192.168.1.85:80:80 -e CACHE_MEM_SIZE=4000m -e CACHE_DISK_SIZE=500g -e CACHE_MAX_AGE=183d steamcache/monolithic:latest
docker run --restart unless-stopped --name sniproxy --detach -p 443:443 steamcache/sniproxy:latest

### DNS Configuration
docker run --restart unless-stopped --name steamcache-dns --detach -p 192.168.1.80:53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP="192.168.1.81 192.168.1.82 192.168.1.83 192.168.1.84" -e WSUSCACHE_IP="192.168.1.85" -e UPSTREAM_DNS=1.1.1.1 steamcache/steamcache-dns:latest

**Comment by BurningTheSky** [comment]
I just opened the Microsoft store and that doesn't work either. Is this expected behaviour?

**Comment by BurningTheSky** [comment]
Is anyone else seeing this issue?

**Comment by wofnull** [comment]
i have the same issue, but this is somewhat DNS related and needs to be looked into from the DNS team

**Comment by danielniedermeyer** [comment]
The problem seems to be that the steam update information is cached. Steam is getting it from this URL: `http://client-download.steampowered.com/client/steam_client_win32`. A quick workaround would be to remove `client-download.steampowered.com` from the cached domains, but then the client update itself also won't be cached.
Is there a way to bypass this URL in the nginx configuration without affecting other content on the same domain?

**Comment by danielniedermeyer** [comment]
Update: tried removing `client-download.steampowered.com`, but didn't help. Still getting an outdated steam version, but don't see any cache hits while updating/installing now. When I change the dns server to skip the cache the update is available. Not sure what's going on here

**Comment by MathewBurnett** [comment]
its possible that something has changed since everything was moved over to lancachenet/monolithic, lancachenet/lancache-dns and lancachenet/sniproxy. its well worth updating to use the latest images and seeing if your issue persists

**Comment by unspec** [comment]
Closing as the original submission appears inactive. Plus Steam hostnames in general will be resolved under their new update - see https://github.com/lancachenet/monolithic/issues/85
