### ISSUE TITLE
Error Changing Upstream DNS

### ISSUE THREAD

**Issue by KsuCraig** [lancachenet/monolithic#55]
I'm receiving an error when trying to alter the upstream dns as instructed.

Running docker run --restart unless-stopped --name lancache-dns -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=192.168.0.25 -e UPSTREAM_DNS="9.9.9.9 149.112.112.112" -e CACHE_M
AX_AGE=200d lancachenet/lancache-dns:latest

Returns this:
finished bootstrapping.
Executing hook /hooks/supervisord-pre.d/10_config_check.sh
checking Bind9 config
/etc/bind/named.conf.options:12: missing ';' before '149.112.112.112'
Problem with Bind9 configuration - Bailing
ERROR: hook /hooks/supervisord-pre.d/10_config_check.sh} returned a non-zero exit status '0'

Leaving out the upstream change allowed it to start correctly.

**Comment by thecodeassassin** [comment]
The lancache-dns container requires you to set multiple upstream servers like so:

UPSTREAM_DNS: "1.1.1.1;1.0.0.1"

While the main sni-proxy container requires it like this:

UPSTREAM_DNS: "1.1.1.1 1.0.0.1"

This probably needs to be changed in the documentation.

**Comment by unspec** [comment]
This should be resolved by https://github.com/lancachenet/generic/issues/97

**Comment by unspec** [comment]
#97 was merged and should have resolved this
