### ISSUE TITLE
Playstation 302 Header Errors

### ISSUE THREAD

**Issue by KsuCraig** [lancachenet/monolithic#60]
### Describe the issue you are having
```
Receiving "unexpected status code 302 in slice response while reading response header from upstream" errors on playstation caching.
```

### How are you running the container(s)?
```
docker run --restart unless-stopped --name lancache-dns --detach -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=192.168.0.25 -e UPSTREAM_DNS="9.9.9.9;149.112.112.112" lancachenet/lancache-dns:latest
docker run --restart unless-stopped --name lancache --detach -v /home/user/cache/data:/data/cache -v /mnt/logs:/data/logs -p 80:80 -e UPSTREAM_DNS="9.9.9.9 149.112.112.112"  lancachenet/monolithic:latest
docker run --restart unless-stopped --name lancache-sniproxy --detach -p 443:443 -e UPSTREAM_DNS="9.9.9.9 149.112.112.112" lancachenet/sniproxy:latest
```

### DNS Configuration
```
Router is directing all systems to the DNS.
```
### Output of container(s)
```
2019/10/02 08:37:59 [error] 1817#1817: *2484 unexpected status code 302 in slice response while reading response header from upstream, client: 192.168.0.226, server: , request: "GET /gs2/ppkgo/prod/CUSA07022_00/178/f_25375fa9ae011b3580d173f79416e588b81c8f20123de80188ea6a75c0612b1a/f/UP1477-CUSA07022_00-FORTNITETESTING1-A0238-V0100_0.pkg?downloadId=00000e38&du=0000000000000e3800e253e85c6e4184&product=0184&threadId=0&serverIpAddr=192.168.0.25&r=00000001&downloadType=om HTTP/1.1", subrequest: "/gs2/ppkgo/prod/CUSA07022_00/178/f_25375fa9ae011b3580d173f79416e588b81c8f20123de80188ea6a75c0612b1a/f/UP1477-CUSA07022_00-FORTNITETESTING1-A0238-V0100_0.pkg", upstream: "http://69.28.165.0:80/gs2/ppkgo/prod/CUSA07022_00/178/f_25375fa9ae011b3580d173f79416e588b81c8f20123de80188ea6a75c0612b1a/f/UP1477-CUSA07022_00-FORTNITETESTING1-A0238-V0100_0.pkg?downloadId=00000e38&du=0000000000000e3800e253e85c6e4184&product=0184&threadId=0&serverIpAddr=192.168.0.25&r=00000001&downloadType=om", host: "gs2.ww.prod.dl.playstation.net"

```

**Comment by N1ghtm4r3x** [comment]
Having the same issues, by default status 302 won't be stored according  20_cache.conf, added the slice size from 1m to 700m just to see what would happen, and i edited it to accept 302 instead of blocking it, neither worked for me, and yes i cleared the cache after editing the file.

**Comment by reapingdarkly** [comment]
I'm seeing the same errors in my log and it stops caching after a few hundred meg, is there a way around this?

**Comment by joseph743** [comment]
I am facing the same issue, is there any solution for this ?

**Comment by RAFd3v** [comment]
> I'm seeing the same errors in my log and it stops caching after a few hundred meg, is there a way around this?

same here. any fixes meanwhile?

**Comment by RAFd3v** [comment]
> Having the same issues, by default status 302 won't be stored according 20_cache.conf, added the slice size from 1m to 700m just to see what would happen, and i edited it to accept 302 instead of blocking it, neither worked for me, and yes i cleared the cache after editing the file.
> 
> for people that dont know the location of the file in the container: /etc/nginx/sites-available/generic.conf.d/root/20_cache.conf

what changes did you make to accept instead of blocking it?

**Comment by VibroAxe** [comment]
So it looks like we have a working fix for this, i just need to recode it into a more elloquant code base and then submit. Will get to it soon!
