### ISSUE TITLE
Origin not cached, all else is

### ISSUE THREAD

**Issue by JohnBFrm** [lancachenet/monolithic#61]
### Describe the issue you are having
I am not seeing games on Origin picked up by the cache, but other services such as Steam and Blizzard's Battle.net app are cached as intended. This is in Stockholm, Sweden. Typical behavior for HTTPS traffic, but Origin shouldn't be downloading games over HTTPS?

### How are you running the container(s)?
```
Exactly as per the readme except the location of the storage for the lancache container, since my host has it on /lancache and not /data.
```

### DNS Configuration
```
The run command is directly from the readme. Device points at the host IP.
```
### Output of container(s)
```
I'll happily dump any logs that you might need, just type out the path of them to me.
```

**Comment by unspec** [comment]
Sadly Origin is currently downloading games over HTTPS for the last few months - see https://github.com/uklans/cache-domains/issues/98 for details, but that explains why you won't see it getting cached currently.

**Comment by JohnBFrm** [comment]
Thanks @unspec, I was looking around to see if something like that had been reported but didn't find anything.

**Comment by bobland1** [comment]
I have the same issue, has their been an update? I am running sniproxy, which is meant to convert HTTPs Traffic right?

**Comment by JohnBFrm** [comment]
> I have the same issue, has their been an update? I am running sniproxy, which is meant to convert HTTPs Traffic right?

No update as far as I know.
Sniproxy forwards HTTPS traffic since we have no insight in its payload, so we just forward it. This is the root of the issue and why we're hoping Origin will eventually not use HTTPS for their CDNs.

**Comment by VibroAxe** [comment]
No official update we can give atm beyond nothing yet, watch this space

**Comment by bobland1** [comment]
Alright, sounds good. Thank you anyway

**Comment by plh1511** [comment]
Am I understanding correctly that the sniproxy container doesn't help to cache Origin content? It just lets the Origin launcher function normally (without caching) while other services are being cached?

**Comment by JohnBFrm** [comment]
> Am I understanding correctly that the sniproxy container doesn't help to cache Origin content? It just lets the Origin launcher function normally (without caching) while other services are being cached?

Yes. The proxy simply allows us to pass HTTPS content as if there was no cache in place since there is nothing we can do with the encrypted payload.

**Comment by unspec** [comment]
Closing this issue - we are tracking Origins related efforts here: https://github.com/uklans/cache-domains/issues/98
