### ISSUE TITLE
Stuck at CRIT set uid to user 0

### ISSUE THREAD

**Issue by ShazerHD** [lancachenet/monolithic#62]
### Describe the issue you are having
When I try to install lancachenet/monolithic the install gets stuck at Stuck at CRIT set uid to user 0
### How are you running the container(s)?
sudo docker run --restart unless-stopped --name lancache -v /cache/data:/data/cache -v /cache/logs:/data/logs -p 10.0.0.102:80:80 lancachenet/monolithic:latest
### DNS Configuration
I haven't set that up yet because I'm stuck at installing monolithic
### Output of container(s)
https://pastebin.com/xppu99Bt

**Comment by VibroAxe** [comment]
This is actually an oddity with supervisord running as root. All is ok!

**Comment by BigJoeS** [comment]
> 
> 
> This is actually an oddity with supervisord running as root. All is ok!

I am trying to understand what "All is ok" means. I am trying to trouble shoot the same issue and can't find a resolution.

Thanks.

**Comment by VibroAxe** [comment]
The crit error isn't actually an error. It's supervisord informing us that it is running as root (nginx is chrooted to the nginx user). 

You should see activity in the access.log if your DNS is configured correctly

**Comment by BigJoeS** [comment]
Thanks. I worked out to just terminate the ssh session and open a new ssh session for each container. Now checking docker all three containers are active.

I had also installer supervisord as it wasn't previous install on this vm for me.

Unsure of the reason each contain was not returning to standard prompt.

**Comment by VibroAxe** [comment]
You shouldn't need to have installed supervisord on the VM host, that's not how docker works
I suspect your docker run command is missing --detach
