### ISSUE TITLE
Monitor the amount of cache data served

### ISSUE THREAD

**Issue by yurividal** [lancachenet/monolithic#66]
Hi Guys, Im not sure if this is the best place to ask this question. Feel free to close the issue if its not.
Im wondering what would be the best way to know how much cached data has been served by my lancache?
Is there a way to know this per-game?

Also, is Windows and Apple updates working fine? We use to purchase MAC minis for all of our LANs to use them as Apple Cache servers, but if lancache is reliable enough, we might move to it.

**Comment by Lepidopterist** [comment]
Some of the larger LAN's ingest their access.log into an Elasticsearch cluster, and use Logstash grok filters to pick out information such as the individual games.

The specific Logstach config, and the Elasticsearch dashboards can be found in the unsupported repo here: https://github.com/lancachenet/logstash

The basic architecture is to run FileBeat on the cache box, sending the data to a Logstash instance, which then manipulates the data and ingests into Elasticsearch.

Our Logstash configs were derived from the original https://github.com/zeropingheroes/lancache-elk configuration, and are specifically configured for Monolithic's log format.  You can see examples of the dashboards etc on the ZPH github repo.

**Comment by unspec** [comment]
Closing as inactive. Feel free to open an issue for further information after looking at the above suggestions.
