### ISSUE TITLE
raspberry pi, caching steam showing lots of "MISS"es

### ISSUE THREAD

**Issue by petershaw23** [lancachenet/monolithic#68]
I'm trying out [this docker container for ARM](https://github.com/lancachenet/monolithic/issues/21#issuecomment-515795300) (in my case: raspberry pi 4) by pegasy.
Downloads seem to be quite chunky, and sometimes stop alltogether (steam shows "download quequed", resuming does nothing).

After checking the log, it shows hundreds of lines like this:

```
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:48 +0000] "GET /depot/552501/chunk/389126f8205c2ea99354606772ce7d32ad58f896 HTTP/1.1" 200 1039584 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:48 +0000] "GET /depot/552501/chunk/65f0bee5bf93bf4d2bfa346e2e88ac5084497c70 HTTP/1.1" 200 1041168 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:48 +0000] "GET /depot/552501/chunk/1e2cd0920ab48c65351a96987dea4ef4c2e1a87a HTTP/1.1" 200 1041008 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:49 +0000] "GET /depot/552501/chunk/92a1368baa962d03471800d6c7f2d6c553a8bc6c HTTP/1.1" 200 1003792 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:49 +0000] "GET /depot/552501/chunk/bc639070161b3baf6d404d6be21750412598dc75 HTTP/1.1" 200 396096 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:49 +0000] "GET /depot/552501/chunk/b3a5709f47530284e03523591967f732d73d196d HTTP/1.1" 200 756400 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:49 +0000] "GET /depot/552501/chunk/c8b1b2c450cb66fb60a4fa52066682e753002ee8 HTTP/1.1" 200 900592 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:49 +0000] "GET /depot/552501/chunk/1b3c5a37281cecd619defcffd308a69ea2e7915a HTTP/1.1" 200 979552 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"
[steam] 192.168.0.4 / - - - [06/Nov/2019:19:34:50 +0000] "GET /depot/552501/chunk/4f9560b53b8c5fc3def100defb75dea6a92d5696 HTTP/1.1" 200 378736 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache65-fra1.steamcontent.com" "-"

```

Is this something that can be fixed? I found [a related issue](https://github.com/lancachenet/monolithic/issues/28#issue-437912080), but I'm stuck

**Comment by unspec** [comment]
The presence of MISS entries in the log just means that the file steam is trying to download is not currently in the cache and so it will be downloaded from the internet and added to the cache - you should expect to see that for every chunk of every file of every game the first time steam downloads it. 

The second time you download a game it should show HIT rather than MISS and be delivered from the cache.

Have you managed to download the game fully?

**Comment by petershaw23** [comment]
yes, It seems to work. I was just confused initially, because downloads sometimes stop before finishing. You then have to wait a while before resuming. This can also happen multiple times per download. Also, downloads sometimes are quite slow (1-2 MB/s). 
But that seems to be a general bug with steam, right?

**Comment by jrcichra** [comment]
@petershaw23 I build all the repos with Github Actions and got it working nicely on a Pi4. Give my compose a try: https://github.com/jrcichra/lancache-rpi
