### ISSUE TITLE
Increase slice size?

### ISSUE THREAD

**Issue by arnili** [lancachenet/monolithic#76]
Lancache slices even linear client downloads into 1MB chunks. This is a good thing because it prevents downloading of unneeded blocks, thus saving bandwidth.

Multi 100Mbit/s links are the norm today and nginx's http1.0 (non-pipelined, non-keepalived) requests to backend servers seem to become the bottleneck at around 120 to 180Mbit/s when a single client issues a single, linear and uncached request for a large file.

What are your thoughts on increasing this to maybe 10MB by default or making this configurable?
(I'm aware the cache needs to be purged after a change).

Thank you.

**Comment by VibroAxe** [comment]
Id not be against considering adding a configurable environment variable. @Lepidopterist @mintopia thoughts

**Comment by VibroAxe** [comment]
Having thought on this for a bit of time, if we did this I'd like to find a way to sanity check cache files / a saved config file which prevents a user accidentally invalidating an entire cache

Something like: save the slice size into a file in /cache, read back on start up. If file doesn't match, or a non default has been set with no previous slice file (and cache data existing) then the image will stop until removed/overridden or similar

**Comment by unspec** [comment]
Hi @arnili 

Changing the slice size has been added in the latest version.

See http://lancache.net/docs/advanced/tuning-cache/#tweaking-slice-size for information on how to make use of this - and let us know if you think the documentation is missing anything.

Please note that it does come with some potential downsides (discussed in the above link) and will invalidate any already cached data on your cache if you change the value.

To tidy up the issues, if you choose to test this please post any feedback on this issue: https://github.com/lancachenet/generic/issues/100

Thanks,

**Comment by arnili** [comment]
Thanks alot (y)

**Comment by hyacin75** [comment]
> and let us know if you think the documentation is missing anything.

Hi, yeah, not sure if the documentation has changed since this was posted - but it's missing *how to do it*, like, entirely.  I'm curious specifically for the monolithic container image - as I've read in a few places now that that is supported - but I can't find *anywhere* how to actually do it.  I'm getting about 20-33% of the d/l speed I get sans lancache on my Xbox while using lancache :-(

**Comment by DuzAwe** [comment]
https://lancache.net/docs/containers/monolithic/variables/

**Comment by hyacin75** [comment]
Better late than never, but, yeah, I stopped running this like two years ago since it was actually making my performance worse and I wasn't getting any help to solve that.
