### ISSUE TITLE
Use two different locations to save data?

### ISSUE THREAD

**Issue by orangedude27** [lancachenet/monolithic#84]
This is more of a suggestion or curiosity.

Is there any way to make this a 2 step caching system?
When a set of data becomes 30 days old, but we still wanna keep the data in case there are still downloads later on, can we put it in a different location but still be able to read it from the caching system?

Thanks

**Comment by arnili** [comment]
Maybe handle this on the (virtual) filesystem itself: https://github.com/trapexit/mergerfs

You can simply move around files on the backends as you wish without affecting the merged view the virtual filesystem exposes.

**Comment by MathewBurnett** [comment]
the current CACHE_MAX_AGE default is 10 years i believe. So a file is only dropped from the cache if you have run out of space and the oldest stuff is evicted to make room.
