### ISSUE TITLE
Feature Request: Microsoft Store

### ISSUE THREAD

**Issue by Stogoh** [lancachenet/monolithic#89]
### Describe the issue you are having
Feature Request: Microsoft Store

Is Microsoft Store supported / will it be supported?

**Comment by MathewBurnett** [comment]
If you are able to confirm that something in the store is downloaded via HTTP and provide cdn addresses then we would be able to ensure it is cached. At present it would only be covered if it is included in 

- https://github.com/uklans/cache-domains/blob/master/windowsupdates.txt
- https://github.com/uklans/cache-domains/blob/master/xboxlive.txt

However i do believe that some of the games in the microsoft store are in the xbox cdn's.

**Comment by Lepidopterist** [comment]
Just to add to this - we've definitely had Sea of Thieves in a cache I run personally, so at least some of the Microsoft store has been covered at some point.  I have not validated this recently though.

**Comment by unspec** [comment]
We've tested a Microsoft Store games download and they do hit the cache by way of the windows update / xbox urls already in the system for microsoft.

If there are any hostnames not being captured or certain downloads being missed, then new hostnames can be added at https://github.com/uklans/cache-domains
