### ISSUE TITLE
Steam getting miss'es even after so called update of lancache steamcontent

### ISSUE THREAD

**Issue by maxvat22** [lancachenet/monolithic#90]
sudo docker run \
  --restart unless-stopped -d \
  --name lancache \
  -v /media/netcahe/gamecache/cache/steam/data:/data/cache \
  -v /media/netcache/gamecache/cache/steam/logs:/data/logs \
  -p 192.168.1.126:80:80 \
  lancachenet/monolithic:latest

sudo docker run \
  --restart unless-stopped -d \
  --name lancache-dns \
  -p 192.168.1.126:53:53/udp \
  -e UPSTREAM_DNS=8.8.8.8 \
  -e STEAMCACHE_IP=192.168.1.126 \
  -e ORIGINCACHE_IP=192.168.1.126 \
  -e UPLAYCACHE_IP=192.168.1.126 \
  -e BLIZZARDCACHE_IP=192.168.1.126 \
  lancachenet/lancache-dns:latest

sudo docker run \
 --restart unless-stopped -d \
  --name sniproxy \
  -p 192.168.1.126:443:443 \
  lancachenet/sniproxy:latest

sudo docker exec -it lancache tail -f /data/logs/access.log

this is what i get in logs of : docker exec -it lancache tail -f /data/logs/access.log - if i download something from steam.

[steam] 192.168.1.223 / - - - [27/Jan/2020:15:07:50 +0000] "GET /appinfo/275100/sha/b2388b7a3e5a7e6306821e47a675675f24effcaa.txt.gz HTTP/1.1" 200 1988 "-" "Valve/Steam HTTP Client 1.0" "MISS" "clientconfig.akamai.steamstatic.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:07:50 +0000] "GET /appinfo/12210/sha/c6798c066ccb92a1a72711ab7774dfaded2ea877.txt.gz HTTP/1.1" 200 2334 "-" "Valve/Steam HTTP Client 1.0" "MISS" "clientconfig.akamai.steamstatic.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:44 +0000] "GET /server-status HTTP/1.1" 200 77 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/manifest/2887059265933254853/5 HTTP/1.1" 200 234635 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24242/manifest/6469208572524230226/5 HTTP/1.1" 200 438 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /server-status HTTP/1.1" 200 77 "-" "Valve/Steam HTTP Client 1.0" "HIT" "valve1202.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /server-status HTTP/1.1" 200 77 "-" "Valve/Steam HTTP Client 1.0" "HIT" "cache32-fra1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /server-status HTTP/1.1" 200 77 "-" "Valve/Steam HTTP Client 1.0" "HIT" "cache9-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/5bf24a691b041ce52a1082ace518438c2c56525f HTTP/1.1" 200 8208 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/6b362bfc6e3e5d9e851f0efdcdf6a16e65b7f1eb HTTP/1.1" 200 224 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache9-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/0f77d4c89e75fd1275f6fa3c2a83914a6e47e245 HTTP/1.1" 200 8112 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache32-fra1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/9b737967c35582bc7e38325541f309de064f19e5 HTTP/1.1" 200 217504 "-" "Valve/Steam HTTP Client 1.0" "MISS" "valve1202.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/576acf3947032455c77ebbb78ec5aad5e4b92555 HTTP/1.1" 200 560 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/1ea3bbfec557302f2505e1b0452731d4f83f38dc HTTP/1.1" 200 288 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache9-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/1795f211d96f5f2c066356d29e3b886a1b86716e HTTP/1.1" 200 224 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache9-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/a0237ed83952f39b1540f40a8e6c6eb22e6711d6 HTTP/1.1" 200 63328 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache32-fra1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/51e058a32a9459fb8d831082a000ee2c048625bf HTTP/1.1" 200 496 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/bb8d7e5c1b1af16dcbfd063495e272322bc479fd HTTP/1.1" 200 83488 "-" "Valve/Steam HTTP Client 1.0" "MISS" "valve1202.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:45 +0000] "GET /depot/24241/chunk/ec8c48f20c1f505217596b1f9aadedfc382ed5f9 HTTP/1.1" 200 304 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:46 +0000] "GET /depot/24241/chunk/a1a908b1cf77f69f2daa297577df716d5e4a1efd HTTP/1.1" 200 449472 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache9-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:46 +0000] "GET /depot/24241/chunk/2fe41c1156b519ab641ea66d32093d1d4094b1fb HTTP/1.1" 200 207472 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache32-fra1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:46 +0000] "GET /depot/24241/chunk/eac0a2660bdd12b4e354c95407374e4182fce060 HTTP/1.1" 200 515136 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"
[steam] 192.168.1.223 / - - - [27/Jan/2020:15:08:46 +0000] "GET /depot/24241/chunk/18e417f3fc528a8b2c7aca7f70cda509404d9cdf HTTP/1.1" 200 865888 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache8-vie1.steamcontent.com" "-"

So what's the problem with the misses ? Also i saw that steam is supporting lan cache by lancache.steamcontent.com https://www.reddit.com/r/lanparty/comments/es3nvs/steam_client_now_supports_lancache/ saw it here but dont know how to implement it ...

Other things like blizzard are downloading ok without misse's but at slow speed's...

**Comment by MathewBurnett** [comment]
MISS is simply telling you you didn't have that file. Its not unusual for the steam to ask for a file, get a MISS, download and hand the downloaded slice to the client. That way you never see a HIT, you could confirm this by downloading a game, uninstalling it and then downloading it again (pick something small). You then should see all HIT. Not all clients behave like this and it is possible to have both a MISS and a HIT show up at the first time of asking. In my quick home test I downloaded a small game at the speed of the hard drive I put it on in my second run through. This is because I already know that my cache disk can serve faster than i can pull over a 1Gb network.

As for the lanache.steamcontent.com change, as long as your dns container is up to date then it will be taken care of as the changes have been entered into the cache domains list that the container pulls.

**Comment by maxvat22** [comment]
Ok thank's for the info , tested what you said and it's true but my question is now raised miss if i dont have the file ok but on blizzard it's saying directly hit so why ? Im not a wizard in linux so that's why im questioning

**Comment by MathewBurnett** [comment]
My test cache and the one we use to run LANs do not have these issues. This suggests something is odd on your setup.
 
What are the physical machine are you running your cache on.

- operating system
- disk size
- memory
- network connection
