### ISSUE TITLE
Slow download speed in Battle.net

### ISSUE THREAD

**Issue by amittamari** [lancachenet/monolithic#91]
### Describe the issue you are having
Slow download speed in Battle.net, about 1.5MBps with lancache, and ~10MBps without lancache.

### How are you running the container(s)?
```
docker run --restart unless-stopped --name lancache-dns --detach -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=$HOST_IP lancachenet/lancache-dns:latest
docker run --restart unless-stopped --name lancache --network host --detach -v /cache/data:/data/cache -v /cache/logs:/data/logs lancachenet/monolithic:latest
docker run --restart unless-stopped --name sniproxy --detach -p 443:443 lancachenet/sniproxy:latest

```

### DNS Configuration
Manually set DNS on the client computer (Windows 10 Home)

### Output of container(s)
I'm getting traffic in /data/logs/access.log, but the speed is very slow for some reason.

**Comment by MathewBurnett** [comment]
I wonder if you can provide me a little more information.
- Which game?
- Do you have a snippet of the logs from the time?
- Are you confident that you had spare bandwidth both up and down while you were experiencing the speed issue?
- Can you confirm you get good speeds with other content providers other than battlenet?

**Comment by maxvat22** [comment]
Have the same problem here , downloading speed is the same as he mentioned up with every game i test.

**Comment by MathewBurnett** [comment]
This could be the way clients calculate the moving average of speed. As the real speed seen at the client is 0 until its max speed for a chunk. The client will likely display the average of the last X speeds. Are you able to monitor the bandwidth the cache is pulling through your firewall?

**Comment by amittamari** [comment]
> I wonder if you can provide me a little more information.
> 
> * Which game?
> * Do you have a snippet of the logs from the time?
> * Are you confident that you had spare bandwidth both up and down while you were experiencing the speed issue?
> * Can you confirm you get good speeds with other content providers other than battlenet?

- CoD:MW, haven't tried anything else but I will.
- Yes, but basically I get all HITs and download speed is averging around 1.7MBps.
- I'm certain that I had spare bandwidth, other computers were downloading at normal speeds.
- Yes, Steam downloads at 100+MBps with GTA V.

**Comment by EpicFail113** [comment]
I see similar performance.

**Comment by hotgore** [comment]
Same issue, get about 3MB/s with 12core CPU, 12GB of RAM and on a NVMe drive.

**Comment by unspec** [comment]
Regarding slow initial blizzard downloads:

The latest version of monolithic/generic now supports changing the slice size used by nginx. We've found that increasing from 1m to 8m offers a small performance boost to specific use cases (single user initial downloads of blizzard games in particular). See http://lancache.net/docs/advanced/tuning-cache/#tweaking-slice-size for information on how to make use of this.

Please note that it does come with some potential downsides (discussed in the above link) and will invalidate any already cached data on your cache if you change the value.

To tidy up the issues, if you choose to test this please post any feedback on this issue: https://github.com/lancachenet/generic/issues/100

If you need any other support please see http://lancache.net/support/ or open a new issue.
