### ISSUE TITLE
how change default google dns ( 8.8.8.8 and 8.8.4.4 ) ?

### ISSUE THREAD

**Issue by prozaklob** [lancachenet/monolithic#93]
how to change the standard server dns that lancache-dns uses?
thx

**Comment by unspec** [comment]
See the lancache-dns documentation:

https://github.com/lancachenet/lancache-dns#usage

The UPSTREAM_DNS variable will allow you to do this.

**Comment by prozaklob** [comment]
> See the lancache-dns documentation:
> 
> https://github.com/lancachenet/lancache-dns#usage
> 
> The UPSTREAM_DNS variable will allow you to do this.

oh... im idiot. thx ))))
