### ISSUE TITLE
Issue with speed 300MBPS(37MB/S) steam 24MBPS(3MB/S) uplay/blizzard tried hdd/ssd/m2 ssd speed's are the same.

### ISSUE THREAD

**Issue by maxvat22** [lancachenet/monolithic#94]
So as the title say's i have issue with speed i cant get past 300MBPS not 300MB/s and when i try uplay or blizzard aplication's they dont go beyond 24MBPS , 3MB/s i tried all the possibilities from issues and even more configurations i event tried the speed on hdd , ssd and m2 ssd and still nothing the speed doesnt go upper than 300MBPS  on steam or 24MBPS in uplay/blizzard app it's a dedicated host-lan on ubuntu only for this for caching games the sistem has 8GB DDR4 and an Intel core i5 8500T 1Gbit/s router speed and pc's.

Some help ? i use only one ip by the way and i dont know about how to inscrease dns lookup ip's im no linux guru i know a little that and there and searching on google for answer's but this reache's me out.

**Comment by MathewBurnett** [comment]
If you are looking to rule out a bottleneck in your setup then try this.
- download a game for 10mins ... Hearthstone for example
- stop and then uninstall the game
- then try installing it again
You should now be installing the game from the cache and should be getting the best speed you can. This speed will now be most likely limited by either the disk on the cache, the disk on the target pc or the network connection between you on the cache.

**Comment by maxvat22** [comment]
ur not helping me at all do you ?
