### ISSUE TITLE
Store.steampowered.com

### ISSUE THREAD

**Issue by Coffee0297** [lancachenet/monolithic#95]
Hello, ive just got this container running again. but now i have a problem. https://store.steampowered.com/ dont work for me, at all. 
i have sniproxy, monolith and lancache installd and running.

**Comment by VibroAxe** [comment]
Going to need a bit more information ;) can you upload the access.log for monolithic and the docker log for sniproxy?

Can you also run the following from your windows box

`nslookup lancache.steampowered.com
nslookup store.steampowered.com
nslookup steam.cache.lancache.net`

Could you also give us the full command you used to create the containers? (If you can't remember you can try `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
    assaflavie/runlike <YOUR-CONTAINER>` but it's not guaranteed to work ;) )

**Comment by Coffee0297** [comment]
Thanks, but it works again... i have no idea how or why....

We are using this for a lan party with 300+ members :D so i need to be shure this works :D

I cant find any file named access.log in monolithic docker. 

``` nslookup lancache.steampowered.com
Server:  OpenWrt.lan
Address:  10.0.0.1
*** OpenWrt.lan can't find lancache.steampowered.com: Non-existent domain


nslookup store.steampowered.com
Server:  OpenWrt.lan
Address:  10.0.0.1
Non-authoritative answer:
Name:    store.steampowered.com
Address:  104.94.22.236


nslookup steam.cache.lancache.net
Server:  OpenWrt.lan
Address:  10.0.0.1
*** OpenWrt.lan can't find steam.cache.lancache.net: Non-existent domain ```


-Tonny

**Comment by unspec** [comment]
Hi,

Firstly steam has been having issues today: https://steamstat.us/ so you might find its related to that and not to your cache.

Secondly, your machine seems to be getting DNS results directly from your router (10.0.0.1) which is returning the public IPs of the steam CDN. Are you not handing out the IP of your cache (lancache-dns) as the DNS server to your clients? Without the correct DNS results your cache will not work properly.

Thanks,

**Comment by VibroAxe** [comment]
Pretty sure your original issue is a steamstore issue. As @unspec says your DNS is not setup correctly and is bypassing lancache completly 

There's something a bit odd as you are seeing VERY limited traffic hitting lancache (the server-status requests). Have you set two dns' servers in your dns configuration in openwrt? (Perhaps you could post the output of ipconfig -a for your main network interface on your gaming pc)

You may also find useful information from the `docker logs monolithic` command which is why we ask for the container output in the new issue template.


OOI, What lan are you running?

**Comment by Coffee0297** [comment]
ive just setup a new lan. do this look correct? 
![image](https://user-images.githubusercontent.com/43273303/74043543-dd672500-49c9-11ea-81e1-e9641414422a.png)

thanks so much for the help so far

**Comment by VibroAxe** [comment]
@Coffee0297 looks good, i actually gave the wrong domain in the other post, you should find lancache.steamcontent.com resolving to 10.0.0.45 then you are good to go assuming you now see results in your monolithic log!

**Comment by Coffee0297** [comment]
Thanks, shuld i open a new issue for speed "issue"? or just continue here?
-Tonny

**Comment by VibroAxe** [comment]
Talk us through your issue here first?

**Comment by Coffee0297** [comment]
well im not getting the speed i was hoping for, im getting 40MB pr second from the cache, i have 6-7 15k rpm disks in raid 0 and 2x xeon cpus, 32gb ram.

**Comment by VibroAxe** [comment]
Closed, did you fix this?

**Comment by Coffee0297** [comment]
i fixd the store.steam issue, i still have issue with throughput tho. made a new issue regarding that
