### ISSUE TITLE
LACP crashes lancache-dns

### ISSUE THREAD

**Issue by Coffee0297** [lancachenet/monolithic#98]
hello, im trying to get lcap bonding to work BUT lancache-dns keeps restarting after 20s... and its allways 20s..
any encounter this "bug"? 
and is there any that have got it working?

-Tonny

**Comment by VibroAxe** [comment]
What are the logs from the lancache-dns container, what command did you use to run it?

Please use the issue template, we ask for the information for a reason :(

**Comment by Coffee0297** [comment]
I have not found any documentation where its stated what command i can run to get a log from lancache_dns. the only i can find is for lancache. 
ive lookd inside the docker and i cant see any log file.

-Tonny

**Comment by VibroAxe** [comment]
`docker logs <container name>` is the actual container output ignoring any additional log files things like bind/nginx might create

So assuming you used our default run up, `docker logs lancache-dns`

**Comment by Coffee0297** [comment]
ahhhhhhhh see i did not now that :D ill get a log and see if i can find an error, thanks. 
fyi imo i wuld revisit the docs so there is explanations of the commands and how to get log from __all__ containers.

-Tonny

**Comment by MathewBurnett** [comment]
As docker logs is a standard feature we hadn't really thought about it. However we have been talking about diagnostics advice recently so maybe we can flesh something out

**Comment by Coffee0297** [comment]
i wuld also gladly help if i had some more knowledge of docker and lancache.. sadly i dont.

-Tonny

**Comment by VibroAxe** [comment]
@Coffee0297 if you can just upload the logs to pastebin / gist or similar we can probably give you an idea on the problem. It's most likely configuration

**Comment by Coffee0297** [comment]
hmm i just got it running with LACP but no issues now... only thing i changed  is that i did not change the load balancing mode.. before i changed it a cupple of times to see where i get the fastest speed. 

-Tonny

**Comment by MathewBurnett** [comment]
I expect that the container was having issues fetching the git repo and restarting to retry.

**Comment by Coffee0297** [comment]
yea prop... ill close this and if i have issues again ill reopen and give a log
